### ISSUE TITLE
Type 'checkboxes'  doesn't work as expected

### ISSUE THREAD

**Issue by argan** [jsonform/jsonform#272] opened 2020-05-08 10:58 UTC
The example 'Multiple options: the checkboxes type'

Expect :
&lt;input type=checkbox name='menu' value='starter'>
&lt;input type=checkbox name='menu' value='maincourse'>
&lt;input type=checkbox name='menu' value='cheese'>
...

But now:
&lt;input type=checkbox name='menu[0]' value='1'>
&lt;input type=checkbox name='menu[1]' value='1'>
&lt;input type=checkbox name='menu[2]' value='1'>
...

**Comment by argan** [comment] 2020-05-08 11:27
I saw the '_jsonform_checkboxes_as_array' trick, but I can't get values from submitted object.

**Comment by tchapi** [comment] 2020-05-08 11:27
Can you share your json schema ?

**Comment by argan** [comment] 2020-05-08 11:53
You can try the demo https://jsonform.github.io/jsonform/playground/index.html?example=fields-checkboxes 

My schema is almost the same.

**Comment by tchapi** [comment] 2020-05-10 14:51
Well ... the example is pretty straightforward and works well. If you add a submit button, you will get the values correctly:

```
{
  "menu": [
    "starter",
    "maincourse"
  ]
}
```

What problem are you facing ?

**Comment by tchapi** [comment] 2020-05-18 10:01
I'm closing this since there's apparently no bug — please feel free to reopen with a reproducible example if you still encounter issues
Thanks

**Closed by tchapi** 2020-05-18 10:01 UTC
