### ISSUE TITLE
Load Different Json Schema Conditionally

### ISSUE THREAD

**Issue by WaqarSarfaraz** [jsonform/jsonform#258] opened 2020-01-22 10:46 UTC
Hey I want to show different schemas conditionally like if user select car then car template will load on that screen & if user select Property Template then Property Schema Load on Screen....

Thanks in Advance....

**Comment by tchapi** [comment] 2020-01-22 13:38
I guess it's a duplicate of https://github.com/jsonform/jsonform/issues/256

**Closed by tchapi** 2020-01-22 13:38 UTC
