### ISSUE TITLE
Offset column not working 

### ISSUE THREAD

**Issue by Lakhwinder00** [jsonform/jsonform#345] opened 2021-05-20 04:36 UTC

**Comment by sdetweil** [comment] 2021-05-21 12:57
could u explain with more detail.. I don't know what offset column means

**Comment by Lakhwinder00** [comment] 2021-05-21 16:07
Spouse, I have one row in the container but I want should textbox place on the right side. I have faced some issue with  move columns to the right using .offset-md-* classes

**Comment by tchapi** [comment] 2021-06-02 07:35
Closing for now as it seems to be bootstrap related (and not properly detailed anyway with a reproducible example, etc)

**Closed by tchapi** 2021-06-02 07:35 UTC
