### ISSUE TITLE
Expanded Fieldset + Default TabIndex set - Collapse issue (bug)

### ISSUE THREAD

**Issue by activatedigital** [jsonform/jsonform#435] opened 2023-06-07 12:13 UTC
Json:
```{"schema":{"friends":{"type":"array","items":{"type":"object","title":"Friend","properties":{"nick":{"type":"string","title":"Nickname"},"animals":{"type":"array","items":{"type":"string","title":"Animal name"}}}}}},"form":[{"type":"tabarray","items":{"type":"section","legend":"{{idx}}. {{value}}","items":[{"type":"fieldset","title":"About","expandable":true,"items":[{"key":"friends[].nick","valueInLegend":true}]},{"type":"fieldset","title":"Animals","expandable":true,"items":[{"type":"tabarray","items":[{"type":"section","legend":"{{idx}}. {{value}}","items":[{"key":"friends[].animals[]","valueInLegend":true}]}]}]}]}}]}```

Issue: 
- When adding a new tabArray element, the collapse is showing the fields but the collapse toggle is in the collapsed position. Clicking on the collapse header puts the header in the expanded state, but hides the fields
- Within the collapse group with a tabarray, the tab group is set as default but does not show the fieldset. By clicking on the tab it shows the fieldset.

![Animated of explaination](https://i.imgur.com/ciedlC8.gif)

**Comment by sdetweil** [comment] 2023-06-07 21:09
ok, a little better layout with code block 
```
{
  "schema": {
    "friends": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "Friend",
        "properties": {
          "nick": {
            "type": "string",
            "title": "Nickname"
          },
          "animals": {
            "type": "array",
            "items": {
              "type": "string",
              "title": "Animal name"
            }
          }
        }
      }
    }
  },
  "form": [
    {
      "type": "tabarray",
      "items": {
        "type": "section",
        "legend": "{{idx}}. {{value}}",
        "items": [
          {
            "type": "fieldset",
            "title": "About",
            "expandable": true,
            "items": [
              {
                "key": "friends[].nick",
                "valueInLegend": true
              }
            ]
          },
          {
            "type": "fieldset",
            "title": "Animals",
            "expandable": true,
            "items": [
              {
                "type": "tabarray",
                "items": [
                  {
                    "type": "section",
                    "legend": "{{idx}}. {{value}}",
                    "items": [
                      {
                        "key": "friends[].animals[]",
                        "valueInLegend": true
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
```

so you have a object with a name
and an array of animals

and then you have an array of those

SO you should have  a + which creates a new one of those with both fields.. a name and an array , and a new tab
if we take out the form, we see this
![Screenshot at 2023-06-07 15-59-14](https://github.com/jsonform/jsonform/assets/1498142/ff4ba725-3c3c-436f-9a3c-34db503006fc)

so the problem is in the form 
if u condense iut, you don't need fieldset if there aren't multiple fields.. 
```
{
  "schema": {
    "friends": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "Friend",
        "properties": {
          "nick": {
            "type": "string",
            "title": "Nickname"
          },
          "animals": {
            "type": "array",
            "items": {
              "type": "string",
              "title": "Animal name"
            }
          }
        }
      }
    }
  },
  "form": [
    {
      "type": "tabarray",
      "items": {
        "type": "section",
        "legend": "{{idx}}. {{value}}",
        "items": [
          {
                "key": "friends[].nick",
                "valueInLegend": true
          },
          {
            "type": "tabarray",
            "title": "Animals",
            "items": [
              {
                "type": "section",
                "legend": "{{idx}}. {{value}}",
                "items": [
                  {
                    "key": "friends[].animals[]",
                    "valueInLegend": true
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
```
this looks like  this  on initial open
![Screenshot at 2023-06-07 16-08-07](https://github.com/jsonform/jsonform/assets/1498142/7eb1bf52-0eb4-4c56-9925-5f14fe121e4e)

**Comment by sdetweil** [comment] 2023-12-04 23:34
any feedback, or can we close this issue?

**Comment by sdetweil** [comment] 2024-01-09 14:03
no feedback, closing

**Closed by sdetweil** 2024-01-09 14:03 UTC
Labels: Question
