### ISSUE TITLE
Question: Can you nest selectFieldSet inside an array?

### ISSUE THREAD

**Issue by mviescas** [jsonform/jsonform#140] opened 2015-05-13 16:09 UTC
Using the text/category example from the documentation, would it be possible to create a form that allowed me to ask the question multiple times and fill out a "subform" for each time I select a category? A use case for this might be like a menu. You select burger or hot dog, and then specify the toppings for  each one (with different toppings available for either burger or hot dog) meaning I can fill out 3 different burger and 2 different hot dog orders for a corporate lunch event.

Here is a kludgy example I tried to draft up using the text/category example. It doesn't work as expected  as I have to select text or category over and over and then instead of switching the displayed object, it appends a new one (so I get the selection, a text instance, followed by another text or category instance). My test results come from using the playground.

{
  "schema": {
    "text": {
      "type": "string",
      "title": "Text"
    },
    "category": {
      "type": "string",
      "title": "Category",
      "enum": [
        "Geography",
        "Entertainment",
        "History",
        "Arts",
        "Science",
        "Sports"
      ]
    }
  },
  "form": [
    {
      "type" : "array",
      "items" : {
        "type" : "section",
        "items" : [
      {"type": "selectfieldset",
      "title": "Make a choice",
      "items": [
        {
          "key": "text",
          "legend": "Search by text"
        },
        {
          "key": "category",
          "legend": "Search by category"
        }
      ]  
         } ]
      }

```
},
{
  "type": "submit",
  "title": "Submit"
}
```

  ]
}

**Comment by ulion** [comment] 2015-05-13 21:14
thank you for reporting. I can reproduce it, it is a bug, but still no idea
which code caused this.

2015-05-14 0:09 GMT+08:00 mviescas <notifications@github.com>:

> Using the text/category example from the documentation, would it be
> possible to create a form that allowed me to ask the question multiple
> times and fill out a "subform" for each time I select a category? A use
> case for this might be like a menu. You select burger or hot dog, and then
> specify the toppings for each one (with different toppings available for
> either burger or hot dog) meaning I can fill out 3 different burger and 2
> different hot dog orders for a corporate lunch event.
>
> Here is a kludgy example I tried to draft up using the text/category
> example. It doesn't work as expected as I have to select text or category
> over and over and then instead of switching the displayed object, it
> appends a new one (so I get the selection, a text instance, followed by
> another text or category instance). My test results come from using the
> playground.
>
> {
> "schema": {
> "text": {
> "type": "string",
> "title": "Text"
> },
> "category": {
> "type": "string",
> "title": "Category",
> "enum": [
> "Geography",
> "Entertainment",
> "History",
> "Arts",
> "Science",
> "Sports"
> ]
> }
> },
> "form": [
> {
> "type" : "array",
> "items" : {
> "type" : "section",
> "items" : [
> {"type": "selectfieldset",
> "title": "Make a choice",
> "items": [
> {
> "key": "text",
> "legend": "Search by text"
> },
> {
> "key": "category",
> "legend": "Search by category"
> }
> ]
>
> } ]
> }
>
> },
> {
>   "type": "submit",
>   "title": "Submit"
> }
>
> ]
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/140>.
>



-- 
Ulion

**Comment by mviescas** [comment] 2015-05-13 21:29
If it helps, I downloaded the version I used yesterday via the "Download ZIP" button on https://github.com/joshfire/jsonform and got this issue.

**Comment by ulion** [comment] 2015-05-13 21:43
No, we need dig into code source to figure out the problem reason, normally
it is caused by some show/hide code confliction

2015-05-14 5:29 GMT+08:00 mviescas <notifications@github.com>:

> If it helps, I downloaded the version I used yesterday via the "Download
> ZIP" button on https://github.com/joshfire/jsonform and got this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/140#issuecomment-101821571>.
>



-- 
Ulion

**Comment by stutteringp0et** [comment] 2017-12-02 05:49
In an array the correct item is visible on load but doesn't change with the select is changes.

It's worse in a tabarray

none of the items are hidden, ever.

**Comment by tchapi** [comment] 2018-06-29 15:47
_I'm closing this issue since it is probably outdated — Please reopen if you still need help on this. Thanks_

**Closed by tchapi** 2018-06-29 15:47 UTC
Labels: Question

**Comment by leoMehlig** [comment] 2018-10-26 14:58
I face the same problem currently. Here a small sample config:
```json
{
    "schema": {
        "friends": {
            "type": "array",
            "items": {
                "type": "object",
                "title": "Friend",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": [
                            "a",
                            "b"
                        ]
                    }
                }
            }
        }
    },
    "form": [
        {
            "type": "tabarray",
            "items": {
                "type": "section",
                "items": [
                    {
                        "type": "selectfieldset",
                        "key": "friends[].action",
                        "items": [
                            {
                                "type": "help",
                                "helpvalue": "This should only show if a is selected"
                            },
                            {
                                "type": "help",
                                "helpvalue": "This should only show if b is selected"
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```
